name: Update Yandex Reviews

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install

    - name: Run parser
      run: python parser.py

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add reviews.json
        git commit -m "update: refresh Yandex reviews" || echo "No changes to commit"
        git push
- name: Install Playwright
  run: |
    pip install -r requirements.txt
    playwright install
